# Generated by Django 5.2 on 2025-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matias_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
