# Generated by Django 5.2 on 2025-04-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matias_aplicacion', '0002_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
